// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgfXZGuH9bnTIIx0RINUZ1UMWcYCIVZOA',
    appId: '1:329415771135:web:a9281febd452254ace5dca',
    messagingSenderId: '329415771135',
    projectId: 'women-safety-badge',
    authDomain: 'women-safety-badge.firebaseapp.com',
    storageBucket: 'women-safety-badge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgfXZGuH9bnTIIx0RINUZ1UMWcYCIVZOA',
    appId: '1:329415771135:android:a9281febd452254ace5dca',
    messagingSenderId: '329415771135',
    projectId: 'women-safety-badge',
    storageBucket: 'women-safety-badge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71lxYXr3NFIVntItUO7Nbm4tDjabBK-U',
    appId: '1:329415771135:ios:09221c6a3825d921ce5dca',
    messagingSenderId: '329415771135',
    projectId: 'women-safety-badge',
    storageBucket: 'women-safety-badge.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyBadge',
  );
}
